import { Toaster } from 'react-hot-toast';
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "فرانت وب آکادمی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="fa">
      <body>
         {/* {!shouldHideNavbar && <Navbar />} */}
        <main>
            <Toaster position="top-left" reverseOrder={false} />
            {children}
        </main>
      </body>
    </html>
  );
}
