// 'use client'
// import { usePathname } from 'next/navigation';
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";




export const metadata: Metadata = {
  title: "فرانت وب آکادمی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const hideNavbarPaths = ['/apnel/student-dashborad'];
  
  // const shouldHideNavbar = hideNavbarPaths.some(path => pathname.startsWith(path));


  return (
    <html lang="fa">
      <body>
         {/* {!shouldHideNavbar && <Navbar />} */}
         <Navbar />
        <main>
            {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
